//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentOnline.Application.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentOnline.Application.Resources.Languages.Lang.en-US", typeof(Lang_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account verification operation is completed..
        /// </summary>
        internal static string AccountVerificationOperationIsCompleted {
            get {
                return ResourceManager.GetString("AccountVerificationOperationIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active user verification is not found..
        /// </summary>
        internal static string ActiveUserVerificationIsNotFound {
            get {
                return ResourceManager.GetString("ActiveUserVerificationIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Added New Comment To Treatment!.
        /// </summary>
        internal static string AdminAddedNewCommentToTreatmentAsHeader {
            get {
                return ResourceManager.GetString("AdminAddedNewCommentToTreatmentAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin {0} added new comment to {1}. treatment..
        /// </summary>
        internal static string AdminAddedNewCommentToTreatmentTemplate {
            get {
                return ResourceManager.GetString("AdminAddedNewCommentToTreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin is created..
        /// </summary>
        internal static string AdminIsCreated {
            get {
                return ResourceManager.GetString("AdminIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct visual file is created..
        /// </summary>
        internal static string CbctVisualFileIsCreated {
            get {
                return ResourceManager.GetString("CbctVisualFileIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct visual file is deleted..
        /// </summary>
        internal static string CbctVisualFileIsDeleted {
            get {
                return ResourceManager.GetString("CbctVisualFileIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct visual file is updated..
        /// </summary>
        internal static string CbctVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("CbctVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cephalometry visual file is updated..
        /// </summary>
        internal static string CephalometryVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("CephalometryVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic information is created..
        /// </summary>
        internal static string ClinicInformationIsCreated {
            get {
                return ResourceManager.GetString("ClinicInformationIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing scan visual file is updated..
        /// </summary>
        internal static string ClosingScanVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("ClosingScanVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is invalid..
        /// </summary>
        internal static string CodeIsInvalid {
            get {
                return ResourceManager.GetString("CodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is added to treatment..
        /// </summary>
        internal static string CommentIsAddedToTreatment {
            get {
                return ResourceManager.GetString("CommentIsAddedToTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is created..
        /// </summary>
        internal static string CommentIsCreated {
            get {
                return ResourceManager.GetString("CommentIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Added New Comment To Treatment!.
        /// </summary>
        internal static string DoctorAddedNewCommentToTreatmentAsHeader {
            get {
                return ResourceManager.GetString("DoctorAddedNewCommentToTreatmentAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor {0} added new comment to {1}. treatment..
        /// </summary>
        internal static string DoctorAddedNewCommentToTreatmentTemplate {
            get {
                return ResourceManager.GetString("DoctorAddedNewCommentToTreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is created..
        /// </summary>
        internal static string DoctorIsCreated {
            get {
                return ResourceManager.GetString("DoctorIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is not found..
        /// </summary>
        internal static string DoctorIsNotFound {
            get {
                return ResourceManager.GetString("DoctorIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation email is sended to user..
        /// </summary>
        internal static string EmailActivationEmailIsSendedToUser {
            get {
                return ResourceManager.GetString("EmailActivationEmailIsSendedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already used..
        /// </summary>
        internal static string EmailIsAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not sended..
        /// </summary>
        internal static string EmailIsNotSended {
            get {
                return ResourceManager.GetString("EmailIsNotSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is sended..
        /// </summary>
        internal static string EmailIsSended {
            get {
                return ResourceManager.GetString("EmailIsSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification service is deactive..
        /// </summary>
        internal static string EmailNotificationServiceIsDeactive {
            get {
                return ResourceManager.GetString("EmailNotificationServiceIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password incorrect..
        /// </summary>
        internal static string EmailOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("EmailOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails are listed..
        /// </summary>
        internal static string EmailsAreListed {
            get {
                return ResourceManager.GetString("EmailsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails are not found..
        /// </summary>
        internal static string EmailsAreNotFound {
            get {
                return ResourceManager.GetString("EmailsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dent Online Verification!.
        /// </summary>
        internal static string EmailVerificationHeader {
            get {
                return ResourceManager.GetString("EmailVerificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, you can verify to your account with this link. {0}.
        /// </summary>
        internal static string EmailVerificationTemplate {
            get {
                return ResourceManager.GetString("EmailVerificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are converted to binary..
        /// </summary>
        internal static string FilesAreConvertedToBinary {
            get {
                return ResourceManager.GetString("FilesAreConvertedToBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are generated..
        /// </summary>
        internal static string FilesAreGenerated {
            get {
                return ResourceManager.GetString("FilesAreGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender should equal M or W..
        /// </summary>
        internal static string GenderShouldEqualMorW {
            get {
                return ResourceManager.GetString("GenderShouldEqualMorW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intra oral is generated..
        /// </summary>
        internal static string IntraOralIsGenerated {
            get {
                return ResourceManager.GetString("IntraOralIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last comment is not found..
        /// </summary>
        internal static string LastCommentIsNotFound {
            get {
                return ResourceManager.GetString("LastCommentIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last comment owner role is not found..
        /// </summary>
        internal static string LastCommentOwnerRoleIsNotFound {
            get {
                return ResourceManager.GetString("LastCommentOwnerRoleIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login operation is success..
        /// </summary>
        internal static string LoginOperationIsSuccess {
            get {
                return ResourceManager.GetString("LoginOperationIsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower jaw visual file is updated..
        /// </summary>
        internal static string LowerJawVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("LowerJawVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Treatment is Created!.
        /// </summary>
        internal static string NewTreatmentIsCreatedAsHeader {
            get {
                return ResourceManager.GetString("NewTreatmentIsCreatedAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your account..
        /// </summary>
        internal static string PleaseVerifyYourAccount {
            get {
                return ResourceManager.GetString("PleaseVerifyYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is expired..
        /// </summary>
        internal static string RefreshTokenIsExpired {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is generated..
        /// </summary>
        internal static string RefreshTokenIsGenerated {
            get {
                return ResourceManager.GetString("RefreshTokenIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is created by {0} at {1} to the system..
        /// </summary>
        internal static string SendNotificationWhenCreatedATreatmentTemplate {
            get {
                return ResourceManager.GetString("SendNotificationWhenCreatedATreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick people information is created..
        /// </summary>
        internal static string SickPeopleInformationIsCreated {
            get {
                return ResourceManager.GetString("SickPeopleInformationIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick people information is manipulated..
        /// </summary>
        internal static string SickPeopleInformationIsManipulated {
            get {
                return ResourceManager.GetString("SickPeopleInformationIsManipulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick people visual file is updated..
        /// </summary>
        internal static string SickPeopleVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("SickPeopleVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The treatment is dont have cbct visual file..
        /// </summary>
        internal static string TheTreatmentIsDontHaveCbctVisualFile {
            get {
                return ResourceManager.GetString("TheTreatmentIsDontHaveCbctVisualFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is expired..
        /// </summary>
        internal static string ThisCodeIsExpired {
            get {
                return ResourceManager.GetString("ThisCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens are generated..
        /// </summary>
        internal static string TokensAreGenerated {
            get {
                return ResourceManager.GetString("TokensAreGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is brought..
        /// </summary>
        internal static string TreatmentIsBrought {
            get {
                return ResourceManager.GetString("TreatmentIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is created..
        /// </summary>
        internal static string TreatmentIsCreated {
            get {
                return ResourceManager.GetString("TreatmentIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is not created..
        /// </summary>
        internal static string TreatmentIsNotCreated {
            get {
                return ResourceManager.GetString("TreatmentIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is not found..
        /// </summary>
        internal static string TreatmentIsNotFound {
            get {
                return ResourceManager.GetString("TreatmentIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments are listed..
        /// </summary>
        internal static string TreatmentsAreListed {
            get {
                return ResourceManager.GetString("TreatmentsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments are not found..
        /// </summary>
        internal static string TreatmentsAreNotFound {
            get {
                return ResourceManager.GetString("TreatmentsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} treatment statu can not be added after {1} treatment statu..
        /// </summary>
        internal static string TreatmentStatuCanNotBeAddedAfterTreatmentStatu {
            get {
                return ResourceManager.GetString("TreatmentStatuCanNotBeAddedAfterTreatmentStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment statu is created..
        /// </summary>
        internal static string TreatmentStatuIsCreated {
            get {
                return ResourceManager.GetString("TreatmentStatuIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment statu is not added to treatment..
        /// </summary>
        internal static string TreatmentStatuIsNotAddedToTreatment {
            get {
                return ResourceManager.GetString("TreatmentStatuIsNotAddedToTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment statu is not created..
        /// </summary>
        internal static string TreatmentStatuIsNotCreated {
            get {
                return ResourceManager.GetString("TreatmentStatuIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper jaw visual file is updated..
        /// </summary>
        internal static string UpperJawVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("UpperJawVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User access token is generated..
        /// </summary>
        internal static string UserAccessTokenIsGenerated {
            get {
                return ResourceManager.GetString("UserAccessTokenIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is brought..
        /// </summary>
        internal static string UserIsBrought {
            get {
                return ResourceManager.GetString("UserIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is created..
        /// </summary>
        internal static string UserIsCreated {
            get {
                return ResourceManager.GetString("UserIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found..
        /// </summary>
        internal static string UserIsNotFound {
            get {
                return ResourceManager.GetString("UserIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles are listed..
        /// </summary>
        internal static string UserRolesAreListed {
            get {
                return ResourceManager.GetString("UserRolesAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles are not found..
        /// </summary>
        internal static string UserRolesAreNotFound {
            get {
                return ResourceManager.GetString("UserRolesAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role is unknown..
        /// </summary>
        internal static string UserRolesIsUnknown {
            get {
                return ResourceManager.GetString("UserRolesIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are listed..
        /// </summary>
        internal static string UsersAreListed {
            get {
                return ResourceManager.GetString("UsersAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are not found..
        /// </summary>
        internal static string UsersAreNotFound {
            get {
                return ResourceManager.GetString("UsersAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification is generated..
        /// </summary>
        internal static string UserVerificationIsGenerated {
            get {
                return ResourceManager.GetString("UserVerificationIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web client url is not found..
        /// </summary>
        internal static string WebClientUrlIsNotFound {
            get {
                return ResourceManager.GetString("WebClientUrlIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send a verification notification to you..
        /// </summary>
        internal static string WeSendAVerificationNotificationToYou {
            get {
                return ResourceManager.GetString("WeSendAVerificationNotificationToYou", resourceCulture);
            }
        }
    }
}
