//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentOnline.Application.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_tr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_tr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentOnline.Application.Resources.Languages.Lang.tr-TR", typeof(Lang_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim reddedildi..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap doğrulama işlemi tamamlandı..
        /// </summary>
        internal static string AccountVerificationOperationIsCompleted {
            get {
                return ResourceManager.GetString("AccountVerificationOperationIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif kullanıcı doğrulaması bulunamadı..
        /// </summary>
        internal static string ActiveUserVerificationIsNotFound {
            get {
                return ResourceManager.GetString("ActiveUserVerificationIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili, Tedaviye Yeni Yorum Ekledi..
        /// </summary>
        internal static string AdminAddedNewCommentToTreatmentAsHeader {
            get {
                return ResourceManager.GetString("AdminAddedNewCommentToTreatmentAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili {0}, {1}. tedaviye yeni yorum ekledi...
        /// </summary>
        internal static string AdminAddedNewCommentToTreatmentTemplate {
            get {
                return ResourceManager.GetString("AdminAddedNewCommentToTreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici oluşturuldu..
        /// </summary>
        internal static string AdminIsCreated {
            get {
                return ResourceManager.GetString("AdminIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct görsel dosyası oluşturuldu..
        /// </summary>
        internal static string CbctVisualFileIsCreated {
            get {
                return ResourceManager.GetString("CbctVisualFileIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct görsel dosyası silindi..
        /// </summary>
        internal static string CbctVisualFileIsDeleted {
            get {
                return ResourceManager.GetString("CbctVisualFileIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbct görsel dosyası güncellendi..
        /// </summary>
        internal static string CbctVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("CbctVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefalometrik görsel dosya güncellendi..
        /// </summary>
        internal static string CephalometryVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("CephalometryVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinik bilgileri oluşturuldu..
        /// </summary>
        internal static string ClinicInformationIsCreated {
            get {
                return ResourceManager.GetString("ClinicInformationIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapanış tarama görsel dosyası güncellendi..
        /// </summary>
        internal static string ClosingScanVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("ClosingScanVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod geçerli değil..
        /// </summary>
        internal static string CodeIsInvalid {
            get {
                return ResourceManager.GetString("CodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum, tedaviye eklendi..
        /// </summary>
        internal static string CommentIsAddedToTreatment {
            get {
                return ResourceManager.GetString("CommentIsAddedToTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum oluşturuldu..
        /// </summary>
        internal static string CommentIsCreated {
            get {
                return ResourceManager.GetString("CommentIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor Yeni Yorum Ekledi!.
        /// </summary>
        internal static string DoctorAddedNewCommentToTreatmentAsHeader {
            get {
                return ResourceManager.GetString("DoctorAddedNewCommentToTreatmentAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor {0}, {1}. tedaviye yeni yorum ekledi..
        /// </summary>
        internal static string DoctorAddedNewCommentToTreatmentTemplate {
            get {
                return ResourceManager.GetString("DoctorAddedNewCommentToTreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor oluşturuldu..
        /// </summary>
        internal static string DoctorIsCreated {
            get {
                return ResourceManager.GetString("DoctorIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor bulunamadı..
        /// </summary>
        internal static string DoctorIsNotFound {
            get {
                return ResourceManager.GetString("DoctorIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğrulama e-postası kullanıcıya gönderildi..
        /// </summary>
        internal static string EmailActivationEmailIsSendedToUser {
            get {
                return ResourceManager.GetString("EmailActivationEmailIsSendedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresi zaten kullanılıyor..
        /// </summary>
        internal static string EmailIsAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta gönderilemedi..
        /// </summary>
        internal static string EmailIsNotSended {
            get {
                return ResourceManager.GetString("EmailIsNotSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta gönderildi..
        /// </summary>
        internal static string EmailIsSended {
            get {
                return ResourceManager.GetString("EmailIsSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta ile bilgilendirme hizmeti deaktif..
        /// </summary>
        internal static string EmailNotificationServiceIsDeactive {
            get {
                return ResourceManager.GetString("EmailNotificationServiceIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta ya da şifre yanlış..
        /// </summary>
        internal static string EmailOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("EmailOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postalar listelendi..
        /// </summary>
        internal static string EmailsAreListed {
            get {
                return ResourceManager.GetString("EmailsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postalar bulunamadı..
        /// </summary>
        internal static string EmailsAreNotFound {
            get {
                return ResourceManager.GetString("EmailsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dent Online Doğrulaması!.
        /// </summary>
        internal static string EmailVerificationHeader {
            get {
                return ResourceManager.GetString("EmailVerificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba, bu bağlantıyla hesabınızı doğrulayabilirsiniz. {0}.
        /// </summary>
        internal static string EmailVerificationTemplate {
            get {
                return ResourceManager.GetString("EmailVerificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyalar binary&apos;e çevrildi..
        /// </summary>
        internal static string FilesAreConvertedToBinary {
            get {
                return ResourceManager.GetString("FilesAreConvertedToBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyalar üretildi..
        /// </summary>
        internal static string FilesAreGenerated {
            get {
                return ResourceManager.GetString("FilesAreGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet, M ya da W içermelidir..
        /// </summary>
        internal static string GenderShouldEqualMorW {
            get {
                return ResourceManager.GetString("GenderShouldEqualMorW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağız içi üretildi..
        /// </summary>
        internal static string IntraOralIsGenerated {
            get {
                return ResourceManager.GetString("IntraOralIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son yorum bulunamadı..
        /// </summary>
        internal static string LastCommentIsNotFound {
            get {
                return ResourceManager.GetString("LastCommentIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son yorum sahibinin rolü bulunamadı..
        /// </summary>
        internal static string LastCommentOwnerRoleIsNotFound {
            get {
                return ResourceManager.GetString("LastCommentOwnerRoleIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı..
        /// </summary>
        internal static string LoginOperationIsSuccess {
            get {
                return ResourceManager.GetString("LoginOperationIsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt çene görsel dosyası güncellendi..
        /// </summary>
        internal static string LowerJawVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("LowerJawVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Tedavi Oluşturuldu!.
        /// </summary>
        internal static string NewTreatmentIsCreatedAsHeader {
            get {
                return ResourceManager.GetString("NewTreatmentIsCreatedAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen hesabını doğrula..
        /// </summary>
        internal static string PleaseVerifyYourAccount {
            get {
                return ResourceManager.GetString("PleaseVerifyYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenileme tokeninin süresi bitmiş..
        /// </summary>
        internal static string RefreshTokenIsExpired {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenileme tokeni üretildi..
        /// </summary>
        internal static string RefreshTokenIsGenerated {
            get {
                return ResourceManager.GetString("RefreshTokenIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme {0} tarafından {1} tarihinde yeni bir tedavi süreci eklendi..
        /// </summary>
        internal static string SendNotificationWhenCreatedATreatmentTemplate {
            get {
                return ResourceManager.GetString("SendNotificationWhenCreatedATreatmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta bilgileri oluşturuldu..
        /// </summary>
        internal static string SickPeopleInformationIsCreated {
            get {
                return ResourceManager.GetString("SickPeopleInformationIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta bilgileri manipüle edildi..
        /// </summary>
        internal static string SickPeopleInformationIsManipulated {
            get {
                return ResourceManager.GetString("SickPeopleInformationIsManipulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta görsel dosyası güncellendi..
        /// </summary>
        internal static string SickPeopleVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("SickPeopleVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu tedavide cbct görsel dosyası yok..
        /// </summary>
        internal static string TheTreatmentIsDontHaveCbctVisualFile {
            get {
                return ResourceManager.GetString("TheTreatmentIsDontHaveCbctVisualFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kodun geçerlilik süresi bitmiş..
        /// </summary>
        internal static string ThisCodeIsExpired {
            get {
                return ResourceManager.GetString("ThisCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenler üretildi..
        /// </summary>
        internal static string TokensAreGenerated {
            get {
                return ResourceManager.GetString("TokensAreGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi getirildi..
        /// </summary>
        internal static string TreatmentIsBrought {
            get {
                return ResourceManager.GetString("TreatmentIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi oluşturuldu..
        /// </summary>
        internal static string TreatmentIsCreated {
            get {
                return ResourceManager.GetString("TreatmentIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi oluşturulamadı..
        /// </summary>
        internal static string TreatmentIsNotCreated {
            get {
                return ResourceManager.GetString("TreatmentIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi bulunamadı..
        /// </summary>
        internal static string TreatmentIsNotFound {
            get {
                return ResourceManager.GetString("TreatmentIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedaviler listelendi..
        /// </summary>
        internal static string TreatmentsAreListed {
            get {
                return ResourceManager.GetString("TreatmentsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavilar bulunamadı..
        /// </summary>
        internal static string TreatmentsAreNotFound {
            get {
                return ResourceManager.GetString("TreatmentsAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tedavi durumu, {1}&apos;den sonra eklenemez..
        /// </summary>
        internal static string TreatmentStatuCanNotBeAddedAfterTreatmentStatu {
            get {
                return ResourceManager.GetString("TreatmentStatuCanNotBeAddedAfterTreatmentStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi statüsü oluşturuldu..
        /// </summary>
        internal static string TreatmentStatuIsCreated {
            get {
                return ResourceManager.GetString("TreatmentStatuIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi statüsü, tedaviye eklenemedi..
        /// </summary>
        internal static string TreatmentStatuIsNotAddedToTreatment {
            get {
                return ResourceManager.GetString("TreatmentStatuIsNotAddedToTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedavi statüsü oluşturulamadı..
        /// </summary>
        internal static string TreatmentStatuIsNotCreated {
            get {
                return ResourceManager.GetString("TreatmentStatuIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst çene görsel dosyası güncellendi..
        /// </summary>
        internal static string UpperJawVisualFileIsUpdated {
            get {
                return ResourceManager.GetString("UpperJawVisualFileIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı erişim tokeni üretildi..
        /// </summary>
        internal static string UserAccessTokenIsGenerated {
            get {
                return ResourceManager.GetString("UserAccessTokenIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı getirildi..
        /// </summary>
        internal static string UserIsBrought {
            get {
                return ResourceManager.GetString("UserIsBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı oluşturuldu..
        /// </summary>
        internal static string UserIsCreated {
            get {
                return ResourceManager.GetString("UserIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        internal static string UserIsNotFound {
            get {
                return ResourceManager.GetString("UserIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı rolleri listelendi..
        /// </summary>
        internal static string UserRolesAreListed {
            get {
                return ResourceManager.GetString("UserRolesAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı rolleri bulunamadı..
        /// </summary>
        internal static string UserRolesAreNotFound {
            get {
                return ResourceManager.GetString("UserRolesAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı rolü bilinmiyor..
        /// </summary>
        internal static string UserRolesIsUnknown {
            get {
                return ResourceManager.GetString("UserRolesIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar listelendi..
        /// </summary>
        internal static string UsersAreListed {
            get {
                return ResourceManager.GetString("UsersAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar bulunamadı..
        /// </summary>
        internal static string UsersAreNotFound {
            get {
                return ResourceManager.GetString("UsersAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı doğrulama üretildi..
        /// </summary>
        internal static string UserVerificationIsGenerated {
            get {
                return ResourceManager.GetString("UserVerificationIsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web client linki bulunamadı..
        /// </summary>
        internal static string WebClientUrlIsNotFound {
            get {
                return ResourceManager.GetString("WebClientUrlIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senin için bir doğrulama bildirimi göndereceğiz..
        /// </summary>
        internal static string WeSendAVerificationNotificationToYou {
            get {
                return ResourceManager.GetString("WeSendAVerificationNotificationToYou", resourceCulture);
            }
        }
    }
}
